### ISSUE TITLE
lacking release of 1.3.1

### ISSUE THREAD

**Issue by buzztiaan** [magi-project/magi#12]
please tarball source and add wallet release in github (and maybe the binaries for people into that kinda thing)

**Comment by buzztiaan** [comment]
also add it as branch tree

**Comment by rotzbouf** [comment]
Just tried the linux version of http://coinmagi.org/bin/m-wallet-1.3.1/
I get the below error when starting the wallet:

QXcbConnection: XCB error: 170 (Unknown), sequence: 170, resource id: 90, major code: 146 (Unknown), minor code: 20
Segmentation fault (core dumped)

**Comment by joelao95** [comment]
I added v1.3.1 release, and will make a branch as well.

**Comment by joelao95** [comment]
v1.3.1 release branched.
