### ISSUE TITLE
Can't compile magi-qt on Arch Linux

### ISSUE THREAD

**Issue by rotzbouf** [magi-project/magi#13]
Hi,

I'm trying to compile the gui wallet on my Arch Linux installation. Other coins like litecoin or bitcoin compile fine on the system. So I guess I am missing some dependencie. Would be nice if anyone could provide a hint.

The steps done were:
$ cd magi
$ make clean
$ qmake     (here I even tried with qmake "USE_UPNP=-" and "USE_IPV6=-")
$ make

The error I get is this:
g++ -c -pipe -fstack-protector-all --param ssp-buffer-size=1 -msse2 -O2 -march=i686 -mtune=generic -O2 -pipe -fstack-protector-strong -D_REENTRANT -fdiagnostics-show-option -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -Wstack-protector -fPIC -DQT_GUI -DBOOST_THREAD_USE_LIB -DBOOST_SPIRIT_THREADSAFE -DHAVE_BUILD_INFO -DLINUX -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -Isrc -Isrc/json -Isrc/qt -Isrc/leveldb/include -Isrc/leveldb/helpers -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtCore -Ibuild -isystem /usr/include/libdrm -Ibuild -I/usr/lib/qt/mkspecs/linux-g++ -o build/net.o src/net.cpp
In file included from src/bignum.h:12:0,
                 from src/main.h:8,
                 from src/db.h:8,
                 from src/net.cpp:7:
src/util.h:258:22: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
     return strprintf("%"PRI64d, n);
                      ^
In file included from src/main.h:10:0,
                 from src/db.h:8,
                 from src/net.cpp:7:
src/net.h:322:20: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
             printf("askfor %s   %"PRI64d" (%s)\n", inv.ToString().c_str(), nRequestTime, DateTimeStrFormat("%H:%M:%S", nRequestTime/1000000).c_str());
                    ^
In file included from src/db.h:8:0,
                 from src/net.cpp:7:
src/main.h:712:26: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
         str += strprintf("(hash=%s, nTime=%d, ver=%d, vin.size=%"PRIszu", vout.size=%"PRIszu", nLockTime=%d)\n",
                          ^
src/main.h:712:72: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
         str += strprintf("(hash=%s, nTime=%d, ver=%d, vin.size=%"PRIszu", vout.size=%"PRIszu", nLockTime=%d)\n",
                                                                        ^
src/main.h:1148:16: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
         printf("CBlock(hash=%s, ver=%d, hashPrevBlock=%s, hashMerkleRoot=%s, nTime=%u, nBits=%08x, nNonce=%u, vtx=%"PRIszu", vchBlockSig=%s)\n",
                ^
src/main.h:1405:26: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
         return strprintf("CBlockIndex(nprev=%p, pnext=%p, nFile=%u, nBlockPos=%-6d nHeight=%d, nMint=%s, nMoneySupply=%s, nFlags=(%s)(%d)(%s), nStakeModifier=%016"PRI64x", nStakeModifierChecksum=%08x, hashProofOfStake=%s, prevoutStake=(%s), nStakeTime=%d merkle=%s, hashBlock=%s)",
                          ^
src/net.cpp:894:36: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                             printf("socket recv flood control disconnect (%"PRIszu" bytes)\n", vRecv.size());
                                    ^
src/net.cpp:1237:12: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
     printf("Flushed %d addresses to peers.dat  %"PRI64d"ms\n",
            ^
src/net.cpp:60:1: error: reference to ‘array’ is ambiguous
 array<int, THREAD_MAX> vnThreadsRunning;
 ^~~~~
In file included from src/net.h:9:0,
                 from src/main.h:10,
                 from src/db.h:8,
                 from src/net.cpp:7:
/usr/include/boost/array.hpp:60:11: note: candidates are: template<class T, unsigned int N> class boost::array
     class array {
           ^~~~~
In file included from /usr/include/c++/6.3.1/tuple:39:0,
                 from /usr/include/c++/6.3.1/bits/stl_map.h:63,
                 from /usr/include/c++/6.3.1/map:61,
                 from src/util.h:17,
                 from src/bignum.h:12,
                 from src/main.h:8,
                 from src/db.h:8,
                 from src/net.cpp:7:
/usr/include/c++/6.3.1/array:90:12: note:                 template<class _Tp, unsigned int _Nm> struct std::array
     struct array
            ^~~~~
make: *** [Makefile:2246: build/net.o] Error 1

**Comment by rotzbouf** [comment]
tried to modify net.cpp but still failed. changes reverted

**Comment by rotzbouf** [comment]
Using release 1.2.3.1 from official repo
https://github.com/magi-project/magi/releases/tag/v1.2.3.1

Works fine with 32bit Arch Linux. However, it states to update to 1.3.1

**Comment by rotzbouf** [comment]
Compiling finishes without errors. 

Starting the wallet still fails with error:
QXcbConnection: XCB error

Could be related to QT bug:
https://forum.qt.io/topic/30791/qxcbconnection-xcb-error-165-unknown

**Comment by rotzbouf** [comment]
With Update net.cpp #2, the wallet works fine. The problem I got (QXcbConnection: XCB error) was related to X11 forwarding.

**Comment by joelao95** [comment]
I saw some C++11 warnings; what's your version of Qt? Could you try compiling without C++11 enabled? Basically C++11 is not tested and well supported so far.
