### ISSUE TITLE
RPC calls do not return address type

### ISSUE THREAD

**Issue by cowmix88** [magi-project/magi#2]
Receive and Address book address are returned together in rpc calls (listreceivedbyaddress, getaddressesbyaccount, etc..) with no type flag to distinguish. I think the simplest fix would to just add the type flag when returning an address stating if its Sending or Receiving.

**Comment by magi-project** [comment]
It will be clear by issuing "listreceivedbyaddress" which means looking up those who sending coins. I can flag "listreceivedbyaddress", but seems be unnecessary for "getaddressesbyaccount" since the command distinguishes accounts.

**Comment by cowmix88** [comment]
Ya that would be great, anyway to distinguish would be fine by me. listreceivedbyaddress currently returns all addressed including sending addresses
