### ISSUE TITLE
ERROR: CTxDB::LoadBlockIndex() : hashSyncCheckpoint not loaded

### ISSUE THREAD

**Issue by PeterL73** [magi-project/magi#21]
Magi version v1.4.4.0 (2017-09-13 23:53:41 -0400)
Using OpenSSL version OpenSSL 1.0.2g  1 Mar 2016
Startup time: 09/14/17 04:46:05
Default data directory /home/server/.magi
Used data directory /home/server/.magi
dbenv.open LogDir=/home/server/.magi/database ErrorFile=/home/server/.magi/db.log
Loading block index...
Opening LevelDB in /home/server/.magi/blocks/index
Transaction index version is 72001
Opened LevelDB successfully
LoadBlockIndex(): hashBestChain=f53f72b30ae088d84605  height=1478607  trust=66478861740266  date=09/14/17 04:43:06
ERROR: CTxDB::LoadBlockIndex() : hashSyncCheckpoint not loaded
Magi: Error loading block database
Flush(false)
DBFlush(false) ended               0ms
StopNode()
Flushed 0 addresses to peers.dat  36ms
Flush(true)
DBFlush(true) ended               0ms
Magi exited

**Comment by joelao95** [comment]
The old chain data needs to be removed fully before launching v1.4.4. Have you done this?

**Comment by PeterL73** [comment]
Did not do that, was hoping for a dorp in replacement. Will try today.

**Comment by PeterL73** [comment]
That did the trick. Thank you.
Would it be save to remove listen=0 and connect=104.128.225.215 from magi.conf when using v1.4.4?

**Comment by joelao95** [comment]
Based on our tests, it is safe so far.
