### ISSUE TITLE
armv7 builds

### ISSUE THREAD

**Issue by feldenthorne** [magi-project/magi#4]
The Qt and headless makefiles have been forked to support armv7 building at my github page: [https://github.com/feldenthorne/magi](https://github.com/feldenthorne/magi).

Only a few lines of code were added to allow Qmake and Make to decide whether to use SSE2 instructions or THUMB instructions.

Changes to the QT GUI qmake file:
* lines 130-141 in [magi-qt.pro](https://github.com/feldenthorne/magi/blob/e4568275240d4129e7c4dec6579dd5598ba0628c/magi-qt.pro#L130-141)

Changes to the headless build Makefile:
* lines 101-113 in [src/makefile-arm](https://github.com/feldenthorne/magi/blob/e4568275240d4129e7c4dec6579dd5598ba0628c/src/makefile.arm#L101-113) (altered version of [makefile.unix](https://github.com/feldenthorne/magi/blob/e4568275240d4129e7c4dec6579dd5598ba0628c/src/makefile.unix))

I would've submitted a pull request, but the binaries have to be built with libdb5.1 instead of libdb4.8 due to limitations with officially supported packages in the official Linaro repositories. Since that goes against the official usage of 4.8, I wasn't sure if it'd be in good taste to suggest a merge right off the bat.

Let me know if you'd like me to submit a pull request, otherwise I'll be happy to keep the fork (reasonably) updated and to release binaries as necessary.

**Comment by magi-project** [comment]
Yes, please submit a pull request. Thanks.

**Comment by feldenthorne** [comment]
Alright - [pull request](https://github.com/magi-project/magi/pull/5) submitted!
