### ISSUE TITLE
enabling PoS crashing wallet

### ISSUE THREAD

**Issue by S0litaire** [magi-project/magi#43]
Running ubuntu 17.10
Wallet:
version : "v1.4.5.1",
protocolversion : 71064,
walletversion : 60000,

Whenever i enable PoS mining either through the gui or the command like the wallet crashes.
This started after passing the HF block 1606950.

The log has the following error :

EXCEPTION: 12bignum_error       
CBigNum::operator/ : BN_div failed       
Magi in ThreadStakeMiner()

**Comment by ParaplegicRacehorse** [comment]
Confirm. Also Ubuntu 17.10
`

  {
    "version" : "v1.4.5.2",
    "protocolversion" : 71064,
    "walletversion" : 60000,
    ...etc.
`

if posii=1 wallet crashes with 

'EXCEPTION: 12bignum_error
CBigNum::operator/ : BN_div failed
Magi in ThreadStakeMiner()'

**Comment by ParaplegicRacehorse** [comment]
![screenshot from 2018-01-05 21-13-17](https://user-images.githubusercontent.com/7605896/34637205-551bb97e-f25d-11e7-847d-61a8d03a3785.png)

**Comment by Youboontoo** [comment]
IIRC, this issue has been resolved in Release v1.4.5.3:

> Bug fix in difficulty adjustment algo, i.e., "MagiQuantumWave"; the bug manifests as an improper data conversion when carrying out a time-domain average because of the trival time difference between blocks.
